require "plist"

fastlane_version "1.63.1"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
    bump_version
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Bump the version number"
  lane :bump_version do
    bump_version
  end

  def bump_version
    build_number = sh("git rev-list --count HEAD").delete("\n")

    # Plists to update
    app_plist = "../Dependn/Info.plist"
    watch_plist = "../Watch/Info.plist"
    watch_ext_plist = "../Watch Extension/Info.plist"

    update_plist_build_number app_plist, build_number
    update_plist_build_number watch_plist, build_number
    update_plist_build_number watch_ext_plist, build_number
  end

  def update_plist_build_number(plist_path, build_number)
    plist_fullpath = File.expand_path(plist_path)
    info_plist = Plist::parse_xml(plist_fullpath)
    info_plist['CFBundleVersion'] = build_number
    File.write(plist_fullpath, info_plist.to_plist)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    gym(scheme: "Dependn")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    gym(scheme: "Dependn")
    deliver(force: true)
  end
end
